### ISSUE TITLE
Load Balancer bandwidth metrics not working

### ISSUE THREAD

**Issue by cheindl** [promhippie/hcloud_exporter#175]
Hi everybody,

it seems, that the bandwidth metrics are not working. I think there is probably a mismatch between API and code: 

The hcloud API returns bandwith information within the fields `bandwith.in` / `bandwidth.out`: Example response:

```
{
    "metrics": {
        "start": "2023-08-04T07:20:00+00:00",
        "end": "2023-08-04T07:20:00+00:00",
        "step": 1,
        "time_series": {
            "bandwidth.in": {
                "values": [
                    [
                        XXXXX,
                        "51111.666667"
                    ]
                ]
            },
            "bandwidth.out": {
                "values": [
                    [
                        XXXXX,
                        "2987717.666667"
                    ]
                ]
            }
        }
    }
}
```

(See also documentation of hcloud API: https://docs.hetzner.cloud/#load-balancers-get-metrics-for-a-loadbalancer)

But the exporter seems to read from fields named `bandwidth_in` /`bandwith_out`:

https://github.com/promhippie/hcloud_exporter/blob/master/pkg/exporter/load_balancer.go#L459
https://github.com/promhippie/hcloud_exporter/blob/master/pkg/exporter/load_balancer.go#L468

I think only the field accesses here must be changed.

**Comment by tboerger** [comment]
What a bad naming convention... @ErwinSteffens I guess this got to be changed to dots, right? I have seen that you contributed the metrics and that I asked if the dot got to be an underscore. Looks like you had it right initially.

**Comment by tboerger** [comment]
https://github.com/promhippie/hcloud_exporter/pull/41 introduced all of that.

**Comment by tboerger** [comment]
I have just pushed the v1.2.3 release.

**Comment by cheindl** [comment]
Thanks! It works now correctly!
