### ISSUE TITLE
Volumes (feature request)

### ISSUE THREAD

**Issue by dual-oo** [promhippie/hcloud_exporter#21]
Hello,

first of all thanks for this useful exporter!
I use your hcloud_exporter for about a week. It is great to visualize the costs of the Hetzner Cloud.
But to calculate the overall costs I need the volume metrics / costs too.
It would be great to have the metrics for the volume feature and/or the loadbalancer in the future too.

thanks in advance

**Comment by tboerger** [comment]
Sounds usefull, I would welcome a contribution :)

**Comment by tboerger** [comment]
This feature will be implemented by https://github.com/promhippie/hcloud_exporter/pull/26
