### ISSUE TITLE
Server metrics exporter only scrapes the first 25 servers

### ISSUE THREAD

**Issue by karsten42** [promhippie/hcloud_exporter#246]
The `server_metrics` exporter only scrapes the first 25 servers since it doesn't use pagination to get the rest. 
[Here](https://github.com/promhippie/hcloud_exporter/blob/c85d19b88287ba089b7fa34eae4d8e378096aaed/pkg/exporter/server_metrics.go#L150-L154) is the code in question.

**Comment by tboerger** [comment]
Fixed, release will follow soon
