### ISSUE TITLE
Failed to parse traffic costs (empty string)

### ISSUE THREAD

**Issue by ValentinVoigt** [promhippie/hcloud_exporter#248]
Hi! Thanks for this very useful plugin. It is very helpful to us. 🎉 

We get the following error message regularly (formatting by me):

```json
{
  "collector": "pricing",
  "err": "strconv.ParseFloat: parsing \"\": invalid syntax",
  "level": "error",
  "msg": "Failed to parse traffic costs",
  "ts": "2024-08-15T13:23:52.90365095Z"
}
```

It looks like some price-related field contains an empty string instead of a float. I'm not entirely sure if this is an actual bug, but it seems not right to me, to log such errors multiple times per minute.

I tried enabling debugging output to get more info, but that does not show anything related to this error. If there's anything I can do to help, please let me know.

_Edit:_ setting `HCLOUD_EXPORTER_COLLECTOR_PRICING` to `false`, unsurprisingly, gets rid of the error

**Comment by ValentinVoigt** [comment]
I was on an old version... 

It happened, because I just copied the example from the [the docs](https://promhippie.github.io/hcloud_exporter/):

```diff
-   image: promhippie/hcloud-exporter:latest
+   image: promhippie/hcloud-exporter:1.0.0
```

Sorry.

**Comment by tboerger** [comment]
No problem, sounds like I should add an automated update to the docs to avoid this confusion in the future.

**Comment by psy** [comment]
> -   image: promhippie/hcloud-exporter:latest
> +   image: promhippie/hcloud-exporter:1.0.0

so you solved it by downgrading to 1.0.0 while the current version is 1.3.0 and contributors of hcloud exporter applaud to this solution? what the hell? 

i tried different versions yesterday and it seems all of the newer versions have the same problem (maybe the api changed?): they fail parsing traffic costs. so this is definitely an issue of hcloud_exporter and should be fixed.

**Comment by ValentinVoigt** [comment]
> so you solved it by downgrading to 1.0.0 while the current version is 1.3.0 and contributors of hcloud exporter applaud to this solution? what the hell?

No, the patch was supposed to be a quote from the docs, where I copied the version from. It is not a patch you should apply. I edited my comment to make that more clear.

> i tried different versions yesterday and it seems all of the newer versions have the same problem (maybe the api changed?): they fail parsing traffic costs. so this is definitely an issue of hcloud_exporter and should be fixed.

You are right, I was propably mistaken. I noticed the error appearing in the newest version as well. I had planned to reopen this issue, but I am on vacation now and wanted to test again before reopening. Now I'll take your word for it. ;)

So yeah, @tboerger, the upgrade did in fact not fix the error. Sorry again. I'm happy to provide debugging information if necessary next week.

**Comment by tboerger** [comment]
I have not thought that an old version fixes the issue, we where talking about the old version mentioned in the docs.

If these metrics are missing in current versions of the exporter this got to be fixed obviously.

**Comment by tboerger** [comment]
Just have seen why the automated pull requests fail, the traffic information have been dropped at 5th of August: https://github.com/promhippie/hcloud_exporter/pull/240

Since I'm more or less back from vacation I will provide a new version soon which will resolve the broken metrics.

**Comment by psy** [comment]
I'm new to go, but I digged a little bit through the source code the last few days and as far as I see the code returns in case it can't parse an API field and therefore the following metrics are not parsed in that case. That doesn't sound right. Shouldn't it just throw a warning and continue parsing the other metrics? 

for example: the pricing metrics are parsed until https://github.com/promhippie/hcloud_exporter/blob/master/pkg/exporter/pricing.go#L213-L222, which returns after logging the error. volume and loadbalancer prizes are never parsed despite they are valid. shouldn't the return statements be removed?

**Comment by tboerger** [comment]
Fixed by https://github.com/promhippie/hcloud_exporter/pull/240 and a release v2.0.0 will follwo as there are breaking changes within the traffic pricing metrics.
