### ISSUE TITLE
snapshot collector

### ISSUE THREAD

**Issue by WladyX** [promhippie/hcloud_exporter#267]
Is it possible to implement snapshot collector?
Thank you for sharing this cool exporter!

**Comment by tboerger** [comment]
I guess that's something we could integrate

**Comment by WladyX** [comment]
cool, thank you @tboerger!

**Comment by tboerger** [comment]
Just checked the source, snapshots metrics should be available already, it's part of the image collector since an image could be of the types app, system, backup and snapshot.

**Comment by WladyX** [comment]
fount it: `hcloud_image_active{type="snapshot"}`
thank you!
Closing.
