### ISSUE TITLE
Add load balancer metrics

### ISSUE THREAD

**Issue by ErwinSteffens** [promhippie/hcloud_exporter#39]
We would like to have load balancer metrics added to this. 

API end-point: https://docs.hetzner.cloud/#load-balancers-get-metrics-for-a-loadbalancer

Suggested metric names:

`hcloud_loadbalancer_open_connections`
`hcloud_loadbalancer_connections_per_second`
`hcloud_loadbalancer_ requests_per_second`
`hcloud_loadbalancer_open_connections_bandwidth_in`
`hcloud_loadbalancer_open_connections_bandwidth_out`

We can work on this, but we are not really golang developers, so some help would be great ;-)

**Comment by tboerger** [comment]
That's a good idea, but I need to switch the CI system to GitHub Actions first :)

**Comment by ErwinSteffens** [comment]
PR is here: https://github.com/promhippie/hcloud_exporter/pull/41

**Comment by tboerger** [comment]
Finally this have been released as v1.1.0
